channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.7.4
  - anyio=2.1.0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.3
  - bleach=3.3.0
  - boost-cpp=1.74.0
  - bqplot=0.12.22
  - branca=0.4.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cachetools=4.2.1
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - cfitsio=3.470
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - colorama=0.4.4
  - colour=0.1.5
  - conda=4.9.2
  - conda-package-handling=1.7.2
  - cryptography=3.4.4
  - curl=7.71.1
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - earthengine-api=0.1.252
  - entrypoints=0.3
  - expat=2.2.10
  - ffmpeg=4.3.1
  - ffmpeg-python=0.2.0
  - fiona=1.8.18
  - folium=0.12.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.5
  - future=0.18.2
  - gdal=3.1.4
  - geeadd=0.5.3
  - geemap=0.8.11
  - geocoder=1.38.1
  - geopandas=0.9.0
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - google-api-core=1.25.1
  - google-api-python-client=1.12.8
  - google-auth=1.24.0
  - google-auth-httplib2=0.0.4
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.27.0
  - google-resumable-media=0.5.0
  - googleapis-common-protos=1.52.0
  - googledrivedownloader=0.4
  - grpcio=1.35.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - httplib2=0.19.0
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.7.0
  - importlib_metadata=3.7.0
  - intel-openmp
  - ipyevents=0.8.2
  - ipyfilechooser=0.4.2
  - ipykernel=5.2.0
  - ipyleaflet=0.13.6
  - ipynb-py-convert=0.4.6
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipytree=0.1.8
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.11
  - jupyter_console=6.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.7.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter_server=1.4.1
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - jupyterlab_widgets=1.0.0
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - libarchive=3.5.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcurl=7.71.1
  - libffi=3.3
  - libgdal=3.1.4
  - libglib=2.66.7
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=13.1
  - libprotobuf=3.15.2
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libsolv=0.7.17
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.10
  - libxslt=1.1.34
  - logzero=1.6.3
  - lxml=4.6.2
  - lz4-c=1.9.3
  - lzo=2.10
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - mamba=0.7.14
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - menuinst
  - mistune=0.8.4
  - mkl=2020.4
  - msys2-conda-epoch
  - multidict=5.1.0
  - munch=2.5.0
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - notebook=6.2.0
  - numpy=1.20.1
  - oauth2client=4.1.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.2
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pcre=8.44
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0.1
  - pixman=0.40.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=13.1
  - proj=7.2.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - prompt_toolkit=3.0.16
  - protobuf=3.15.2
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycosat=0.6.3
  - pycparser=2.20
  - pycrs=1.0.2
  - pydrive=1.3.1
  - pygments=2.8.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.0.0.post1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-box=5.3.0
  - python-dateutil=2.8.1
  - python-mss=6.1.0
  - python_abi=3.8
  - pytz=2021.1
  - pywin32
  - pywinpty
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - ratelim=0.1.6
  - reproc=14.2.1
  - reproc-cpp=14.2.1
  - requests=2.25.1
  - rsa=4.7.2
  - rtree=0.9.7
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.2
  - ruamel_yaml=0.15.80
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - simplejson=3.17.2
  - six=1.15.0
  - sniffio=1.2.0
  - soupsieve=2.2
  - sqlite=3.34.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tiledb=2.2.4
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.58.0
  - traitlets=5.0.5
  - traittypes=0.2.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - uritemplate=3.0.1
  - urllib3=1.26.3
  - vc
  - voila=0.2.7
  - vs2015_runtime
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - whitebox=1.4.0
  - whiteboxgui=0.1.9
  - widgetsnbextension=3.5.1
  - win_inet_pton
  - wincertstore
  - winpty
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8
